port: 8080

modules:
  - default

auth:
  access_token:
    secret: HzDBJ7vFRUQyh88p2ktan0B6Vihn7dcj
    expires_in: 1h
  refresh_token:
    secret: 5Sh54MWy4p9661A21Ygz31V9FpS7MTxX
    expires_in: 365d

database:
  host: localhost
  port: 3306
  username: username
  password: password
  database: database
  rebuild: false

redis:
  host: localhost
  port: 6379
